name: Setup CODESYS Installation in matrix

on:
  push:
    branches:
      - main
      - update-*
      - migrate-*
      - addons-*
    paths-ignore:
      - 'README.md'

jobs:
  setup-installation:
    strategy:
      matrix:
        generation:
          - 3.5.16.0
          - 3.5.20.0
          - 3.5.21.0
        architecture:
          - 32
          - 64
        include:
          - generation: 3.5.16.0
            patch: 3
          - generation: 3.5.20.0
            patch: 0
          - generation: 3.5.20.0
            patch: 1
          - generation: 3.5.20.0
            patch: 3
          - generation: 3.5.21.0
            patch: 2

    runs-on: windows-latest
    permissions:
      contents: read
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup CODESYS
      id: setup_codesys
      uses: ./
      with:
        installer-version: 2.4.1
        auto-update-installer: false
        generation: ${{ matrix.generation }}
        architecture: ${{ matrix.architecture }}
        patch: ${{ matrix.patch }}
    
    - name: Test outputs
      shell: bash
      run: |
        echo "Installer path: ${{ steps.setup_codesys.outputs.installer-path }}"
        echo "Installer executable: ${{ steps.setup_codesys.outputs.installer-cli-executable }}"
        echo "CODESYS Path: ${{ steps.setup_codesys.outputs.codesys-path }}"
        echo "CODESYS executable: ${{ steps.setup_codesys.outputs.codesys-executable }}"

    - name: Upload info files
      uses: actions/upload-artifact@v4
      with:
        if-no-files-found: warn
        name: ${{ matrix.generation }}-${{ matrix.patch }}-${{ matrix.architecture }}-info-files
        path: |
          ${{ steps.setup_codesys.outputs.installation-info-file-path }}
          ${{ steps.setup_codesys.outputs.add-ons-info-file-path }}
    
  # Example/Test 2: job to install CODESYS with add-ons from list
  setup-installation-with-addons-case01:
    runs-on: windows-latest
    permissions:
      contents: read
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
  
    - name: Setup CODESYS
      id: setup_codesys
      uses: ./
      with:
        installer-version: 2.4.1
        auto-update-installer: true
        generation: 3.5.21.0
        patch: 2
        architecture: 64
        install-add-ons: true
        add-ons-list: |
          dd6c2da4-2ed2-4076-9bf7-52394db68819,1.6.0.0
          fb6f3506-d165-4e75-a1b9-98895d542cc8,4.5.0.0
          bd131967-3a89-4e22-a845-79b0be0a3ce1,4.1.0.0

    - name: Upload info files
      uses: actions/upload-artifact@v4
      with:
        if-no-files-found: warn
        name: case01-info-files
        path: |
          ${{ steps.setup_codesys.outputs.installation-info-file-path }}
          ${{ steps.setup_codesys.outputs.add-ons-info-file-path }}

  # Example/Test 2: job to install CODESYS from add-on package file
  setup-installation-with-addons-case02:
    runs-on: windows-latest
    permissions:
      contents: read
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
  
    - name: Setup CODESYS
      id: setup_codesys
      uses: ./
      with:
        installer-version: 2.4.1
        auto-update-installer: true
        generation: 3.5.21.0
        patch: 2
        architecture: 64
        install-add-ons: true
        add-ons-from-file-list: |
          example/custom_packages/NetBaseServices_Example_1.0.0.0.package
          example/custom_packages/Trace_Example_1.0.0.0.package

    - name: Upload info files
      uses: actions/upload-artifact@v4
      with:
        if-no-files-found: warn
        name: case02-info-files
        path: |
          ${{ steps.setup_codesys.outputs.installation-info-file-path }}
          ${{ steps.setup_codesys.outputs.add-ons-info-file-path }}

  # Example/Test 3: job to install CODESYS with add-ons from list and package file
  setup-installation-with-addons-case03:
    runs-on: windows-latest
    permissions:
      contents: read
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
  
    - name: Setup CODESYS
      id: setup_codesys
      uses: ./
      with:
        installer-version: 2.4.1
        auto-update-installer: true
        generation: 3.5.21.0
        patch: 2
        architecture: 64
        install-add-ons: true
        add-ons-list: |
          dd6c2da4-2ed2-4076-9bf7-52394db68819,1.6.0.0
          fb6f3506-d165-4e75-a1b9-98895d542cc8,4.5.0.0
          bd131967-3a89-4e22-a845-79b0be0a3ce1,4.1.0.0
        add-ons-from-file-list: |
          example/custom_packages/NetBaseServices_Example_1.0.0.0.package
          example/custom_packages/Trace_Example_1.0.0.0.package

    - name: Upload info files
      uses: actions/upload-artifact@v4
      with:
        if-no-files-found: warn
        name: case03-info-files
        path: |
          ${{ steps.setup_codesys.outputs.installation-info-file-path }}
          ${{ steps.setup_codesys.outputs.add-ons-info-file-path }}

  # Example/Test 4: job to install CODESYS with custom package file only
  setup-installation-with-addons-case04:
    runs-on: windows-latest
    permissions:
      contents: read
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup CODESYS
      id: setup_codesys
      uses: ./
      with:
        installer-version: 2.4.1
        auto-update-installer: true
        generation: 3.5.21.0
        patch: 2
        architecture: 64
        install-add-ons: true
        add-ons-installer-import-file: example/custom_import_files/example_import_add-ons.installation-config

    - name: Upload info files
      uses: actions/upload-artifact@v4
      with:
        if-no-files-found: warn
        name: case04-info-files
        path: |
          ${{ steps.setup_codesys.outputs.installation-info-file-path }}
          ${{ steps.setup_codesys.outputs.add-ons-info-file-path }}