name: Setup CODESYS Installation

on:
  push: 
    branches: 
      - master

jobs:
  setup-codesys:
    strategy:
      matrix:
        generation:
          - 3.5.16.0
          - 3.5.17.0
          - 3.5.18.0
          - 3.5.19.0
        architecture:
          - 32
          - 64
        include:
          - generation: 3.5.16.0
            patch: 3
          - generation: 3.5.17.0
            patch: 2
          - generation: 3.5.18.0
            patch: 4
          - generation: 3.5.19.0
            patch: 6

    runs-on: windows-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup CODESYS
      uses: ./
      with:
        installer-version: 2.2.2
        generation: ${{ matrix.generation }}
        architecture: ${{ matrix.architecture }}
        patch: ${{ matrix.patch }}
        hotfix: 0
        build: 0
        #installation-directory: C:\CODESYS