name: Setup CODESYS Installation in matrix

on: push

jobs:
  setup-codesys:
    strategy:
      matrix:
        generation:
          - 3.5.16.0
          - 3.5.17.0
          - 3.5.18.0
          - 3.5.19.0
          - 3.5.20.0
        architecture:
          - 32
          - 64
        include:
          - generation: 3.5.16.0
            patch: 3
          - generation: 3.5.17.0
            patch: 2
          - generation: 3.5.18.0
            patch: 4
          - generation: 3.5.19.0
            patch: 6
          - generation: 3.5.20.0
            patch: 0

    runs-on: windows-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup CODESYS
      id: setup_codesys
      uses: ./
      with:
        installer-version: 2.2.2
        generation: ${{ matrix.generation }}
        architecture: ${{ matrix.architecture }}
        patch: ${{ matrix.patch }}
    
    - name: Test outputs
      shell: bash
      run: |
        echo "Installer path: ${{ steps.setup_codesys.outputs.installer-path }}"
        echo "Installer executable: ${{ steps.setup_codesys.outputs.installer-cli-executable }}"
        echo "CODESYS Path: ${{ steps.setup_codesys.outputs.codesys-path }}"
        echo "CODESYS executable: ${{ steps.setup_codesys.outputs.codesys-executable }}"